<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Mark extends Model
{
    use HasFactory;

    protected $table = 'marks';

    public $timestamps = false;

    protected $fillable = [
        'title',
    ];

    public function carModels()
    {
        return $this->hasMany(CarModel::class, 'mark_id', 'id');
    }

    public function car()
    {
        return $this->belongsTo(Car::class);
    }

//    public function delete()
//    {
//        $this->carModel()->delete();
//
//        return parent::delete(); // TODO: Change the autogenerated stub
//    }

}
